-- DB에서 랜덤수 추출
SELECT TRUNC(DBMS_RANDOM.VALUE(1, 11)) FROM DUAL;


-- IF문 (IF 조건 THEN ELSE END IF)
DECLARE
    NUM1 NUMBER := 5;
    NUM2 NUMBER := TRUNC(DBMS_RANDOM.VALUE(1, 11));
BEGIN
    IF NUM1 >= NUM2 THEN 
        DBMS_OUTPUT.PUT_LINE(NUM1 || ' 큰수');
    ELSE  DBMS_OUTPUT.PUT_LINE(NUM2 || ' 큰수');
    END IF;
END;

-- ELSIF문
DECLARE
    RAN_NUM NUMBER := TRUNC(DBMS_RANDOM.VALUE(1, 101));
BEGIN
    IF RAN_NUM >= 90 THEN
        DBMS_OUTPUT.PUT_LINE('A학점 입니다.');
    ELSIF RAN_NUM >= 80 THEN
        DBMS_OUTPUT.PUT_LINE('B학점 입니다.');
    ELSIF RAN_NUM >= 70 THEN
        DBMS_OUTPUT.PUT_LINE('C학점 입니다.');
    ELSE DBMS_OUTPUT.PUT_LINE('공부하세요 낙제입니다.');
    END IF;
END;

/*
첫번째 값은 ROWNUM을 이용한다.
1-120사이의 랜덤한 번호를 이용해서 랜덤 DEPARTMENT_ID의 첫번째 행만 SELECT
뽑은 사람의 SALARY가 9000이상이면 높음, 5000이상이면 중간 나머지는 낮음
*/

SELECT *
FROM DEPARTMENTS;

DECLARE
    NUM1 NUMBER := ROUND(DBMS_RANDOM.VALUE(1, 120), -1);
    EMP_SAL EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT SALARY
    INTO EMP_SAL
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = NUM1 AND ROWNUM = 1;
    
    IF EMP_SAL >= 9000 THEN
        DBMS_OUTPUT.PUT_LINE(EMP_SAL || '높음');
    ELSIF EMP_SAL >= 5000 THEN
        DBMS_OUTPUT.PUT_LINE(EMP_SAL || '중간');
    ELSE DBMS_OUTPUT.PUT_LINE(EMP_SAL || '낮음');
    END IF;
END;