--CASE문
SET SERVEROUTPUT ON;


DECLARE
    SAL EMPLOYEES.SALARY%TYPE;
    RAN NUMBER := ROUND(DBMS_RANDOM.VALUE(1, 120), -1);
BEGIN
    SELECT SALARY
    INTO SAL
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = RAN AND ROWNUM = 1;
    
    CASE WHEN SAL >= 9000 THEN
        DBMS_OUTPUT.PUT_LINE(SAL || '높음');
         WHEN SAL >= 5000 THEN
        DBMS_OUTPUT.PUT_LINE(SAL || '중간');
         ELSE
        DBMS_OUTPUT.PUT_LINE(SAL || '낮음');
    END CASE;
END;